#!/bin/bash
#
# =====================================================================================
#
#       Filename:  climate
#
#    Description:
#
#
#        Version:  0.01
#        License:
#        Created:  11/06/2018 02:21:03 PM
#       Revision:  none
#
#         Author:  ice.zhao (zhao yang)
#         E-Mail:  smallbit@163.com
#   Organization:
#
# =====================================================================================
#
INCLUDE=include

. ${INCLUDE}/local.bh
. ${INCLUDE}/err_type.bh
. ${LIB}/log
. ${LIB}/parse

main() {
    # Usage
    # Check_net_connection
    # if [ "$?" -eq ${ERR_KO} ]; then
    #     echo "network is unavailable."
    #     exit 0
    # fi

    declare -a pkg_src=()
    pkg_src=(`Parse_src ${SRC_DIR}`)

    # install packages
    # ${SUPER} ${LIB_DIR}/install.sh ${pkg_src[*]}

    # setup editor environment
    ${LIB_DIR}/setup-editor.sh

    # Log ${pkg_src[*]}
    exit 0
}



Usage() {
	cat <<- EOF
Usage: ${0##.*/}
	EOF
}



Check_net_connection() {
    local ip_addr='8.8.8.8'
    local cmd=`which ping`

    ${cmd} -c 4 ${ip_addr} > /dev/null

    if [ "$?" -eq 0 ]; then
        return ${ERR_OK}
    else
        return ${ERR_KO}
    fi
}
















main "$1"
